apiVersion: apps/v1

kind: Deployment

metadata:
  name: teleportclient
  namespace: squirrel-operator
  labels:
    app: teleportclient
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teleportclient
  template:
    metadata:
      labels:
        app: teleportclient
    spec:
      volumes:
      - name: config
        projected:
          defaultMode: 511
          sources:
          - secret:
              name: nvidiauseridentitykey
          - configMap:
              name: configs
      containers:
      - name: teleportclient
        image: sarveshdockerrepo/teleportclient:0.0.8
        volumeMounts:
        - name: config
          mountPath: "/config"
      serviceAccountName: squirrel-edge-operator-controller-manager